/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gesturevoicebasedshopping;


import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
//import org.apache.commons.io.FileUtils;



public class ProductDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form StoreFrame
     */
    
    public static String voicestatus="";
    
    public static String path1="";
    public static String path2="";
    public static String path3="";
    public static String path4="";
    public static String pdetails="";
    public static String pname="";
    public static String pdname="";
    public static String price="";
    
    public ProductDetailsFrame() {
        initComponents();
     //   jLabel2.setLocation(400, 50);
         jLabel3.setHorizontalAlignment(JLabel.CENTER);
         jLabel3.setSize(300, 400);
          jLabel4.setText(pdname);
          jLabel5.setText(pdetails);
         jButton2.setOpaque(false);
             
                      
            ImageIcon icon1=new ImageIcon (getClass().getResource(path1));
            Image image1 = icon1.getImage().getScaledInstance(150, 200, Image.SCALE_DEFAULT); // transform it 
            icon1 = new ImageIcon(image1);
           
            
            jLabel3.setIcon(icon1);
            jLabel6.setIcon(resizeIcon(path1));
            jLabel7.setIcon(resizeIcon(path2));
            jLabel8.setIcon(resizeIcon(path3));
            jLabel9.setIcon(resizeIcon(path4));
           
           
      
    }
     ImageIcon resizeIcon(String path)
    {
        ImageIcon icon=new ImageIcon (getClass().getResource(path));
        Image image = icon.getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT); // transform it 
        icon = new ImageIcon(image);
        
        return icon;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Buy Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tenor1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(364, 364, 364))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
           tokenGeneration();
                    
    }//GEN-LAST:event_jButton2ActionPerformed

    void tokenGeneration()
    {
         price=price.replace("₹", "");
         price=price.trim();
         String items="Product: "+pdname+"\n"+"Price: "+price;
         System.out.println("product details: "+items);
         ArrayList temp=new ArrayList();
         temp.add(items);
         temp.add(price);
         DataKeeper.itemlist.add(temp);
         
            this.dispose();
            BuyMoreFrame pf = new BuyMoreFrame();
            ObjectKeeper.pf=pf;
            pf.getContentPane().setBackground(Color.WHITE);
            pf.setVisible(true);
            pf.setExtendedState(MAXIMIZED_BOTH);
            Timer timer = new Timer();
            new java.util.Timer().schedule(new TimerTask(){
        @Override
        public void run() {
            new PlayAudio().playAudio("C://botvoice//askingmore.mp3"); 
        }
    },2000); 
            
        timer.cancel();
        
       
        
    
          
         
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                      funBack();
           
    }//GEN-LAST:event_jButton3ActionPerformed

    void funBack()
    {
        if(pname.equals("phone"))
           {
               ProductFrame.pdname="Apple iPhone 11 Red";
               ProductFrame.path="/mobile1.jpg";
                      
               String str = "<html><b>Price</b>: ₹54,900.00<br/>"
                       + "<b>Model Name</b>: IPhone 11 64GB Red"
                       + "<br/><b>Wireless Carrier</b>: Unlocked for All Carriers"
                       + "<br/><b>Brand</b>: Apple"
                       + "<br/><b>Memory Storage Capacity</b>: 64 GB</html>";
               ProductFrame.pdetails=str;
               ProductFrame.pname = "phone";
               Timer timer = new Timer();
               new java.util.Timer().schedule(new TimerTask(){
            @Override
        public void run() {
            new PlayAudio().playAudio("C://botvoice//phone.mp3"); 
        }
    },1000); 
            
        timer.cancel();
                             
           }
           else if(pname.equals("tv"))
           {
                
               ProductFrame.pdname="Sony W830 HD LED TV";
               ProductFrame.path="/tv1.jpg";
               
               String str = "<html><b>Price</b>: ₹29,900.00"
                       + "<br/><b>Model Name</b>: KD32W830"
                       + "<br/><b>Display Size</b>: 32 (80 Cm)"
                       + "<br/><b>Brand</b>: Sony"
                       + "<br/><b>HD Technology & Resolution</b>: 1366 x 768 Pixels</html>";

               ProductFrame.pdetails=str;
               ProductFrame.pname = "tv";
               Timer timer = new Timer();
            new java.util.Timer().schedule(new TimerTask(){
           @Override
           public void run() {
            new PlayAudio().playAudio("C://botvoice//sony.mp3"); 
        }
    },1000); 
            
        timer.cancel();
                           
                      
           }
           else if(pname.equals("camera"))
           {
              
               ProductFrame.pdname="Sony Handycam";
               ProductFrame.path="/camera1.jpg";
               
               String str = "<html><b>Price</b>: ₹29,900.00"
                       + "<br/><b>Model Name</b>: KD32W830"
                       + "<br/><b>Display Size</b>: 32 (80 Cm)"
                       + "<br/><b>Brand</b>: Sony"
                       + "<br/><b>HD Technology & Resolution</b>: 1366 x 768 Pixels</html>";

               ProductFrame.pdetails=str;
               ProductFrame.pname = "camera";
           
            Timer timer = new Timer();
            new java.util.Timer().schedule(new TimerTask(){
        @Override
        public void run() {
            new PlayAudio().playAudio("C://botvoice//camera.mp3"); 
        }
    },1000); 
            
        timer.cancel();
               
                      
           }
         else if(pname.equals("wmachine"))
           {
                ProductFrame.pdname="LG Washing Machine";
               ProductFrame.path="/wmachine1.jpg";
               
               String str = "<html><b>Price</b>: ₹11,490.00<br/><b>Model Name</b>: P7020NGAZ"
                 + "<br/><b>Brand</b>: LG"
                 + "<br/><b>Colour</b>: Dark Gray"
                 + "<br/><b>Capacity</b>: 7 Kilograms</html>";

               ProductFrame.pdetails=str;
               ProductFrame.pname = "wmachine";
           
            Timer timer = new Timer();
            new java.util.Timer().schedule(new TimerTask(){
        @Override
        public void run() {
            new PlayAudio().playAudio("C://botvoice//machine.mp3"); 
        }
    },1000); 
            
        timer.cancel();
               
                      
           }
        else if(pname.equals("watch"))
           {
                ProductFrame.pdname="Skagen Men's Watch";
               ProductFrame.path="/watch1.jpg";
               
               String str ="<html><b>Price</b>: ₹9,796.00<br/><b>Model Name</b>: SKW6472"
                 + "<br/><b>Brand</b>: Skagen"
                 + "<br/><b>Colour</b>: Black"
                 + "<br/><b>Warranty</b>: 2 years</html>";

               ProductFrame.pdetails=str;
               ProductFrame.pname = "watch";
           
            Timer timer = new Timer();
            new java.util.Timer().schedule(new TimerTask(){
        @Override
        public void run() {
            new PlayAudio().playAudio("C://botvoice//watch.mp3"); 
        }
    },1000); 
            
        timer.cancel();
               
                      
           }
            this.dispose();
            ProductFrame pf = new ProductFrame();
            pf.setVisible(true);
            pf.setExtendedState(MAXIMIZED_BOTH);
            pf.getContentPane().setBackground(Color.WHITE);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
